export const browserCoreExamples = [
  "woodls browser status",
  "woodls browser start",
  "woodls browser stop",
  "woodls browser tabs",
  "woodls browser open https://example.com",
  "woodls browser focus abcd1234",
  "woodls browser close abcd1234",
  "woodls browser screenshot",
  "woodls browser screenshot --full-page",
  "woodls browser screenshot --ref 12",
  "woodls browser snapshot",
  "woodls browser snapshot --format aria --limit 200",
  "woodls browser snapshot --efficient",
  "woodls browser snapshot --labels",
];

export const browserActionExamples = [
  "woodls browser navigate https://example.com",
  "woodls browser resize 1280 720",
  "woodls browser click 12 --double",
  'woodls browser type 23 "hello" --submit',
  "woodls browser press Enter",
  "woodls browser hover 44",
  "woodls browser drag 10 11",
  "woodls browser select 9 OptionA OptionB",
  "woodls browser upload /tmp/woodls/uploads/file.pdf",
  'woodls browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "woodls browser dialog --accept",
  'woodls browser wait --text "Done"',
  "woodls browser evaluate --fn '(el) => el.textContent' --ref 7",
  "woodls browser console --level error",
  "woodls browser pdf",
];
