#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${WOODLS_INSTALL_E2E_IMAGE:-${WOODLS_INSTALL_E2E_IMAGE:-woodls-install-e2e:local}}"
INSTALL_URL="${WOODLS_INSTALL_URL:-${WOODLS_INSTALL_URL:-https://woodls.bot/install.sh}}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
WOODLS_E2E_MODELS="${WOODLS_E2E_MODELS:-${WOODLS_E2E_MODELS:-}}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker/install-sh-e2e"

echo "==> Run E2E installer test"
docker run --rm \
  -e WOODLS_INSTALL_URL="$INSTALL_URL" \
  -e WOODLS_INSTALL_TAG="${WOODLS_INSTALL_TAG:-${WOODLS_INSTALL_TAG:-latest}}" \
  -e WOODLS_E2E_MODELS="$WOODLS_E2E_MODELS" \
  -e WOODLS_INSTALL_E2E_PREVIOUS="${WOODLS_INSTALL_E2E_PREVIOUS:-${WOODLS_INSTALL_E2E_PREVIOUS:-}}" \
  -e WOODLS_INSTALL_E2E_SKIP_PREVIOUS="${WOODLS_INSTALL_E2E_SKIP_PREVIOUS:-${WOODLS_INSTALL_E2E_SKIP_PREVIOUS:-0}}" \
  -e OPENAI_API_KEY="$OPENAI_API_KEY" \
  -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  -e ANTHROPIC_API_TOKEN="$ANTHROPIC_API_TOKEN" \
  "$IMAGE_NAME"
